// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { secondaryDir: string | null, lastSuccessAt: string | null, lastSecondarySuccessAt: string | null, staleWarningDays: number, };
