// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarcodeImportLine } from "./BarcodeImportLine";

export type BarcodeImportPreview = { importId: number, fileName: string, lines: Array<BarcodeImportLine>, linked: number, skipped: number, conflicts: number, canApply: boolean, };
