// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BarcodeImportLine = { productId: number | null, productName: string, unitCode: string | null, cartonCode: string | null, status: string, message: string | null, };
