// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentifierType } from "./IdentifierType";
import type { UsedByProduct } from "./UsedByProduct";

export type CheckBarcodeResult = { available: boolean, detectedType: IdentifierType, checkDigitValid: boolean | null, usedBy: UsedByProduct | null, };
