// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnTarget = "NAME" | "PACK_SIZE" | "STOCK" | "KOLI_CHECK" | "PRICE" | "EXTERNAL_CODE";
