// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputUom } from "./InputUom";
import type { OperationType } from "./OperationType";
import type { ReasonCode } from "./ReasonCode";
import type { ReturnDisposition } from "./ReturnDisposition";
import type { TxSource } from "./TxSource";

export type CommitTxInput = { clientTxnId: string, operatorId: number, productId: number, identifierCode: string | null, operation: OperationType, inputQuantity: number, inputUom: InputUom, reasonCode: ReasonCode | null, returnDisposition: ReturnDisposition | null, acknowledgeNegative: boolean, source: TxSource, notes: string | null, };
