// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type EmployeeInput = { id: number | null, employeeCode: string, name: string, role: Role, };
