// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentifierType = "EAN13" | "EAN8" | "UPCA" | "GTIN14" | "CODE128" | "INTERNAL" | "OTHER";
