// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportIssue } from "./ImportIssue";
import type { MatchStatus } from "./MatchStatus";

export type ImportRowDto = { rowNumber: number, rawName: string, nameKey: string, externalCode: string | null, packSize: number | null, quantity: number | null, koli: number | null, price: number | null, productId: number | null, matchStatus: MatchStatus, issues: Array<ImportIssue>, };
