// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnTarget } from "./ColumnTarget";

export type ImportColumnMap = { source: string, target: ColumnTarget, firstValue: string | null, };
