// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportCounts = { dataRows: number, matched: number, new: number, ambiguous: number, invalid: number, packSizeMissing: number, };
