// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryRow = { productId: number, name: string, modelCode: string | null, externalCode: string | null, packSize: number | null, referencePrice: number | null, baselineQuantity: number, currentQuantity: number, barcodeCount: number, barcodes: Array<string>, lastChangedAt: string | null, baselineAsOf: string | null, openExceptionCount: number, };
