// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarcodeKind } from "./BarcodeKind";

export type LinkBarcodeInput = { productId: number, code: string, kind: BarcodeKind, unitMultiplier: number | null, operatorId: number, };
