// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationType } from "./OperationType";

export type OpCount = { operation: OperationType, count: number, netChange: number, };
