// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationType = "STOCK_IN" | "SALE" | "RETURN" | "ADJUSTMENT" | "REVERSAL" | "RECONCILIATION_ADJUSTMENT";
