// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentifierDto } from "./IdentifierDto";

export type ProductDetail = { productId: number, name: string, modelCode: string | null, externalCode: string | null, packSize: number | null, referencePrice: number | null, locationName: string, baselineQuantity: number, currentQuantity: number, baselineAsOf: string | null, identifiers: Array<IdentifierDto>, lastChangedAt: string | null, openExceptionCount: number, };
