// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProductCard = { productId: number, name: string, modelCode: string | null, packSize: number | null, referencePrice: number | null, locationId: number, baselineQuantity: number, currentQuantity: number, baselineAsOf: string | null, };
