// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentLink = { identifierId: number, code: string, productId: number, productName: string, action: string, createdAt: string, };
