// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentifierDto } from "./IdentifierDto";
import type { ProductCard } from "./ProductCard";

export type ResolveResult = { "kind": "FOUND", card: ProductCard, identifier: IdentifierDto, } | { "kind": "UNKNOWN", code: string, } | { "kind": "PRODUCT_INACTIVE", code: string, productName: string, };
