// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScannerSuffix } from "./ScannerSuffix";

export type ScannerSettings = { maxGapMs: number, minLength: number, idleFlushMs: number, suffix: ScannerSuffix, dedupMs: number, };
