// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

export type ScanSettings = { quickScanEnabled: boolean, fkeysEnabled: boolean, autoCommitOnNextScan: boolean, secondaryLanguage: Language | null, };
