// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpCount } from "./OpCount";

export type SessionSummary = { id: number, sessionNumber: number, operatorId: number, operatorName: string, startedAt: string, lastActivityAt: string, txCount: number, productCount: number, totalUnits: number, netChange: number, byOperation: Array<OpCount>, };
