// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupSettings } from "./BackupSettings";
import type { ImportSettings } from "./ImportSettings";
import type { Language } from "./Language";
import type { ScanSettings } from "./ScanSettings";
import type { ScannerSettings } from "./ScannerSettings";
import type { SessionSettings } from "./SessionSettings";
import type { SoundSettings } from "./SoundSettings";

export type Settings = { companyId: number | null, activeLocationId: number | null, language: Language, setupCompletedAt: string | null, scanner: ScannerSettings, scan: ScanSettings, session: SessionSettings, sound: SoundSettings, backup: BackupSettings, import: ImportSettings, };
