// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupSettingsPatch } from "./BackupSettingsPatch";
import type { ImportSettings } from "./ImportSettings";
import type { Language } from "./Language";
import type { ScanSettings } from "./ScanSettings";
import type { ScannerSettings } from "./ScannerSettings";
import type { SessionSettingsPatch } from "./SessionSettingsPatch";
import type { SoundSettings } from "./SoundSettings";

/**
 * Partial update for `update_settings`. Omitted fields stay as they are.
 */
export type SettingsPatch = { language?: Language, scanner?: ScannerSettings, scan?: ScanSettings, session?: SessionSettingsPatch, sound?: SoundSettings, backup?: BackupSettingsPatch, import?: ImportSettings, };
