// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeInput } from "./EmployeeInput";
import type { Language } from "./Language";
import type { SetupLocationInput } from "./SetupLocationInput";

export type SetupInput = { language: Language, companyName: string, admin: EmployeeInput, employees: Array<EmployeeInput>, location: SetupLocationInput, };
