// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationType } from "./LocationType";

export type SetupLocationInput = { code: string, name: string, locationType: LocationType, };
