// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationDto } from "./LocationDto";

export type StartupState = { setupCompleted: boolean, invariantViolations: number, lastBackupAt: string | null, secondaryBackupStale: boolean, activeLocation: LocationDto | null, companyName: string | null, dataDir: string, appVersion: string, };
