// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileFormat } from "./FileFormat";
import type { ImportColumnMap } from "./ImportColumnMap";
import type { ImportCounts } from "./ImportCounts";
import type { ImportIssue } from "./ImportIssue";
import type { ImportPurpose } from "./ImportPurpose";
import type { ImportRowDto } from "./ImportRowDto";

export type StockReportPreview = { importId: number, purpose: ImportPurpose, fileName: string, fileFormat: FileFormat, companyName: string | null, reportName: string | null, asOfDate: string | null, printedAt: string | null, cutoffAt: string | null, stockColumn: string, stockColumnCandidates: Array<string>, columns: Array<ImportColumnMap>, counts: ImportCounts, fileIssues: Array<ImportIssue>, sampleRows: Array<ImportRowDto>, problemRows: Array<ImportRowDto>, canApply: boolean, };
