// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TxRow } from "./TxRow";

export type TxPage = { rows: Array<TxRow>, nextCursor: number | null, };
