// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationType } from "./OperationType";
import type { SessionSummary } from "./SessionSummary";

export type TxResult = { transactionId: number, clientTxnId: string, operation: OperationType, quantityChange: number, stockBefore: number, stockAfter: number, negativeWarning: boolean, session: SessionSummary, createdAt: string, idempotentReplay: boolean, wasExported: boolean, };
