// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationType } from "./OperationType";

export type TxRow = { id: number, createdAt: string, operatorId: number, operatorName: string, operatorCode: string, productId: number, productName: string, modelCode: string | null, identifierCode: string | null, operation: OperationType, inputQuantity: number, inputUom: string, unitMultiplier: number, quantityChange: number, stockBefore: number, stockAfter: number, sessionNumber: number | null, negativeWarning: boolean, reasonCode: string | null, reversesTransactionId: number | null, syncStatus: string, };
